# Generated by Django 5.2.11 on 2026-03-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_options_attendance_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerequest',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('Sick', 'Sick Leave'), ('Casual', 'Casual Leave'), ('Emergency', 'Emergency Leave'), ('Personal', 'Personal Leave')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
