# Generated by Django 5.2.11 on 2026-03-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancerequest_leave_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Leave', 'Leave'), ('WFH', 'Work From Home'), ('Absent', 'Absent')], default='Present', max_length=20),
        ),
    ]
